#!/bin/bash

if [ "$#" != "1" ] ; then
    echo "bysync-rwatch <config>"
    exit 1
fi

GLOBAL_CONFIG="$HOME/.bysync/_global.conf"
CONFIG=$1
if [ ! -f "$CONFIG" ] ; then
    echo "Config file $CONFIG not found!"
    exit 1
fi

source "$GLOBAL_CONFIG"
source "$CONFIG"

DST_HOST=${DST%%:*}
DST_DIR=${DST#*:}

while [ 1 ] ; do
    ssh "$DST_HOST" \
        timeout "$RWATCH_TIMEOUT" \
        inotifywait -r -e create,delete,modify,move \
        --exclude "$STAMP_REGEXP_PROGRESS" "$DST_DIR"
    bysync-sync "$CONFIG"
done
