#!/bin/bash

if [ "$#" != "1" ] ; then
    echo "bysync-rwatch <config>"
    exit 1
fi

CONFIG=$1
if [ ! -f "$CONFIG" ] ; then
    echo "Config file $CONFIG not found!"
    exit 1
fi

source "$CONFIG"

DST_HOST=${DST%%:*}
DST_DIR=${DST#*:}

echo $DST
echo $DST_HOST
echo $DST_DIR

while [ 1 ] ; do
    ssh "$DST_HOST" \
        inotifywait -r -e create,delete,modify,move \
        --exclude "\.bysync\.stamp.*" "$DST_DIR"
    bysync-sync "$CONFIG"
done
