#!/bin/bash

function Sync {
    CONFIG=$1

    echo "Syncing $CONFIG"
    source "$CONFIG"
    touch "$SRC"
}

if [ "$#" == "1" ] ; then
    CONFIG=$1
    if [ ! -f "$CONFIG" ] ; then
        echo "Config file $CONFIG not found!"
        exit 1
    fi
    Sync "$CONFIG"

else
    for CONFIG in ~/.bysync/*.conf ; do
        # Skip config files starting with underscore
        if [[ $(basename $CONFIG) == _* ]] ; then
            continue
        fi
        Sync "$CONFIG"
    done
fi
